#--------------
# Source: https://www.youtube.com/watch?v=bNgoM8AV0Ec&list=PL3oFDne19J1DaABHtm7PgRcPjA-WKhDeT&index=2
#--------------
version: '3'

services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - confd:/etc/nginx/conf.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - confd:/etc/nginx/conf.d
    environment:
      - DEFAULT_EMAIL=josejcamara+raspberry@gmail.com

  nginx-web:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /home/pi/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=josejcamara.ddns.net
      - LETSENCRYPT_HOST=josejcamara.ddns.net
      - LETSENCRYPT_EMAIL=josejcamara+raspberry@gmail.com

  jenkins-master:
    build: ./jenkins-master
    # expose:
    #   - "8080"
    #   - "50000"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - certs:/etc/nginx/certs:ro
      - jenkins-data:/var/jenkins_home
      - jenkins-log:/var/log/jenkins
    environment:
      - VIRTUAL_HOST=jenkins
    #   - LETSENCRYPT_HOST=josejcamara-jenkins.ddns.net
    #   - LETSENCRYPT_EMAIL=josejcamara+raspberry@gmail.com

volumes:
  certs:
  html:
  vhostd:
  confd:
  jenkins-data:
  jenkins-log:

# networks:
#   jenkins-net:
